### PR TITLE
fixed issues

### LINKED ISSUE #10: Filtering by multiple criteria won't work
https://github.com/jakpop/user-rest-api/blob/bc96cd4788e5ea7819b61eb0538604ba72fe6a8c/src/main/java/com/example/userrestapi/UserController.java#L30

Here you overwrite the search results from searches by previous criteria. Instead, please use _all_ criteria in conjunction (*AND* operator).

### LINKED ISSUE #11: Use of streams instead of imperative code
https://github.com/jakpop/user-rest-api/blob/bc96cd4788e5ea7819b61eb0538604ba72fe6a8c/src/main/java/com/example/userrestapi/UserRepository.java#L31

We don't use imperative programming. Please use Stream API when working on collections. See filter for find methods.

### LINKED ISSUE #12: Use Lombok @Data annotations
https://github.com/jakpop/user-rest-api/blob/bc96cd4788e5ea7819b61eb0538604ba72fe6a8c/src/main/java/com/example/userrestapi/User.java#L19

Lombok provides handy `@Data` annotation that eliminates the need of explicit getters and setters.

### LINKED ISSUE #13: Project structure needs to be more telling
Currently the whole project is in single dir. Please break down the project into functional parts as subdirectories.

### PR DESCRIPTION
**Pull request by jakpop**
- fixed filtering by multiple criteria
- added stream filter in place of imperative code
- corrected project structure
- added lombok annotations

### CODE REVIEW

File: src/main/java/com/example/userrestapi/controller/UserController.java [hunk 1]
```diff
@@ -23,20 +27,37 @@
 
         List<User> users = new ArrayList<User>();
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/controller/UserController.java]:
```suggestion
        List<User> users;
```
the initialization here is not needed as you overwrite that just after

File: src/main/java/com/example/userrestapi/controller/UserController.java [hunk 2]
```diff
@@ -23,20 +27,37 @@
...
 
-        if (name != null) {
+        //I get it this is probably not the most optimal solution,
+        //as with more parameters the amount of conditions is going to raise drastically,
+        //but it's the only one I was able to come up wth right now
+
+        //FIXME find a better solution to this workaround
+        if ((name != null) && (surname != null) && (email != null)) {
+            users = repository.findByName(name).stream().filter(user -> user.getSurname().equals(surname)).collect(Collectors.toList()).
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/controller/UserController.java]: you can use AND in the filter method
```suggestion
            users = repository.findByName(name).stream().filter(user -> user.getSurname().equals(surname) && user.getEmail().equals(email)).collect(Collectors.toList()).
```

File: src/main/java/com/example/userrestapi/controller/UserController.java [hunk 3]
```diff
@@ -23,20 +27,37 @@
...
+                                                stream().filter(user -> user.getEmail().equals(email)).collect(Collectors.toList());
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/controller/UserController.java]:
```suggestion

```

File: src/main/java/com/example/userrestapi/controller/UserController.java [hunk 4]
```diff
@@ -23,20 +27,37 @@
 
         List<User> users = new ArrayList<User>();
 
-        if (name != null) {
+        //I get it this is probably not the most optimal solution,
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/controller/UserController.java]: the easiest way here would be to get all users, as you do in line 58 and then filter it out on each parameter one by one, something like:
users = repository.findAll();
if (name != null) {
    users = users.stream().filter(user -> user.name().equals(name)).collect(Collectors.toList())
}
if (surname != null) {
...
}
etc.
optionally you can also build a stream like that:
Stream<User> userStream = users.stream();
if (name != null) {
    userStream.filter(user -> user.getName().equals(name));
}
...
and at the end collect the results and return.
To make it even prettier you can do all of this in UserRepository in a method findByParams(all params here), so this one would only contain the return. In real life world with a connection to db, this would look more like that

File: src/main/java/com/example/userrestapi/domain/User.java [hunk 5]
```diff
@@ -1,5 +1,8 @@
-package com.example.userrestapi;
+package com.example.userrestapi.domain;
 
+import lombok.Data;
+
+@Data
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/domain/User.java:5]: :+1: for using lombok :slightly_smiling_face:

File: src/main/java/com/example/userrestapi/repository/UserRepository.java [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+
+    public User findById(Long id) {
+        Optional<User> matchingUser = users.stream().filter(user -> user.getId() == id).findFirst();
+
+        User userWithId = new User();
+        if (matchingUser.isPresent()) {
+            userWithId = matchingUser.get();
+        }
+
+        return userWithId;
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/repository/UserRepository.java]: do not return an empty user, just return null

File: src/main/java/com/example/userrestapi/repository/UserRepository.java [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+    public boolean delete(Long id) {
+        return users.removeIf(user -> user.getId() == id);
+    }
+
+    public boolean update(Long id, User updated) {
+        if (updated == null) {
+            return false;
+        }
+        else {
+            if (containsUserWithId(id)) {
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/repository/UserRepository.java]: no need for additional method to check if the user by this id exists, just run findById, and if the result is not null, do the update

File: src/main/java/com/example/userrestapi/controller/UserController.java (hunk 4 above)
Comment (jakpop) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: so if user would have 6 parameters then findByParams() would require 2^6 ifs in it? no other option to do it? cause that's a lot of conditions 😄

Comment (jakpop) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: btw. I've commited fixes to the lines you've commented on. I don't know if this re-request review button works like that cause there wasn't any message about notification being sent to you and it's the first time I'm using it

Comment (pandaive) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: that's 6 ifs :slightly_smiling_face: you get the whole collection, they you filter it out one by one param

Comment (pandaive) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: the "filter" method on stream returns the collection (or a stream in a second case I described before) so you don't need to do "if x and y and z then filter and return" then "if x and y then filter and return" and so on.
You simply do filter on each param one by one starting with whole users array, so in each "if" you will just filter out more values (if params given) and at the end you will end up with final array containing only the Users that pass on criteria that you've given.
users = repository.findAll();
if (name != null) {
users = users.stream().filter(user -> user.name().equals(name)).collect(Collectors.toList())
}
if (surname != null) {
users = users.stream().filter(user -> user.surname().equals(surname)).collect(Collectors.toList())
}
and after those two ifs, your "users" collection will only contain users with name and surname given in param. I hope this time it's clearer, but if you have more question, ask me :slightly_smiling_face:

File: src/main/java/com/example/userrestapi/controller/UserController.java [hunk 8]
```diff
@@ -21,30 +23,16 @@
...
-        users = repository.findAll();
         return new ResponseEntity<>(users, HttpStatus.OK);
     }
 
     @RequestMapping(value = "/{id}", method = RequestMethod.GET)
     public ResponseEntity<User> findUserById(@PathVariable Long id) {
         User user = repository.findById(id);
 
-        if (repository.containsUserWithId(id)) {
+        if (repository.findById(id) != null) {
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/controller/UserController.java]: don't call repository.findById again, you already have this data in "user" variable
```suggestion
        if (user != null) {
```

File: src/main/java/com/example/userrestapi/controller/UserController.java (hunk 4 above)
Comment (jakpop) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: alright, I get it now. thank you 🙂

File: src/main/java/com/example/userrestapi/repository/UserRepository.java [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+
+    public boolean delete(Long id) {
+        return users.removeIf(user -> user.getId() == id);
+    }
+
+    public boolean update(Long id, User updated) {
+        if (updated == null) {
+            return false;
+        }
+        if (findById(id) != null) {
```
Comment (pandaive) [inline src/main/java/com/example/userrestapi/repository/UserRepository.java]: don't call findById(id) twice. Assign it first to a var: User original = findById(id) and then check if original != null, then update

File: src/main/java/com/example/userrestapi/controller/UserController.java (hunk 4 above)
Comment (jakpop) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: sorry to bother you, but I really can't wait to hear about the decision whether it's good or bad (hoping it's the former tho :smile:). is there a possibility someone could give me some information today?

**Review by pandaive — APPROVED** [review]
All good for me, I approve the PR :slightly_smiling_face:

File: src/main/java/com/example/userrestapi/controller/UserController.java (hunk 4 above)
Comment (pandaive) [reply src/main/java/com/example/userrestapi/controller/UserController.java]: sorry, I didn't think about it. It's good now, I approved the pull request. Well done!
